spring:
  application:
    name: authentication
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/auth/realms/master
          jwk-set-uri: http://localhost:8088/protocol/openid-connect/certs