/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Account } from '../models/account';
import { getAllAccounts } from '../fn/accounts/get-all-accounts';
import { GetAllAccounts$Params } from '../fn/accounts/get-all-accounts';

@Injectable({ providedIn: 'root' })
export class AccountsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllAccounts()` */
  static readonly GetAllAccountsPath = '/transactions/accounts';

  /**
   * get all accounts data.
   *
   * get it all
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAccounts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts$Response(params?: GetAllAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<Account>> {
    return getAllAccounts(this.http, this.rootUrl, params, context);
  }

  /**
   * get all accounts data.
   *
   * get it all
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAccounts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccounts(params?: GetAllAccounts$Params, context?: HttpContext): Observable<Account> {
    return this.getAllAccounts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Account>): Account => r.body)
    );
  }

}
