/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Account } from '../models/account';
import { findAllCustom } from '../fn/graphs/find-all-custom';
import { FindAllCustom$Params } from '../fn/graphs/find-all-custom';
import { getAccount } from '../fn/graphs/get-account';
import { GetAccount$Params } from '../fn/graphs/get-account';
import { Graph } from '../models/graph';

@Injectable({ providedIn: 'root' })
export class GraphsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllCustom()` */
  static readonly FindAllCustomPath = '/graphs/findAll';

  /**
   * get all the graph.
   *
   * get it all
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllCustom()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCustom$Response(params?: FindAllCustom$Params, context?: HttpContext): Observable<StrictHttpResponse<Graph>> {
    return findAllCustom(this.http, this.rootUrl, params, context);
  }

  /**
   * get all the graph.
   *
   * get it all
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllCustom$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCustom(params?: FindAllCustom$Params, context?: HttpContext): Observable<Graph> {
    return this.findAllCustom$Response(params, context).pipe(
      map((r: StrictHttpResponse<Graph>): Graph => r.body)
    );
  }

  /** Path part for operation `getAccount()` */
  static readonly GetAccountPath = '/graphs/accountNumber/{accountNumber}';

  /**
   * simple test get.
   *
   * simple test get
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccount$Response(params: GetAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<Account>> {
    return getAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * simple test get.
   *
   * simple test get
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccount(params: GetAccount$Params, context?: HttpContext): Observable<Account> {
    return this.getAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<Account>): Account => r.body)
    );
  }

}
