server:
  port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/micro
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: admin123