/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Graph } from '../../models/graph';

export interface FindAllCustom$Params {
}

export function findAllCustom(http: HttpClient, rootUrl: string, params?: FindAllCustom$Params, context?: HttpContext): Observable<StrictHttpResponse<Graph>> {
  const rb = new RequestBuilder(rootUrl, findAllCustom.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Graph>;
    })
  );
}

findAllCustom.PATH = '/graphs/findAll';
