/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Graph {
  nodes?: Array<{
'id'?: number;
'label'?: string;
}>;
  relationships?: Array<{
'id'?: number;
'from'?: number;
'to'?: number;
}>;
}
