spring:
  application:
    name: transactions
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/micro
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:1235/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform:
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084

